# Generated by Django 5.2.8 on 2026-05-19 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='cars.brand')),
            ],
        ),
        migrations.CreateModel(
            name='CompleteSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='cars.carmodel')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('color', models.CharField(choices=[('black', 'Черный'), ('white', 'Белый'), ('gray', 'Серый'), ('red', 'Красный'), ('green', 'Зеленый')], max_length=20)),
                ('body_type', models.CharField(choices=[('sedan', 'Седан'), ('suv', 'Внедорожник'), ('coupe', 'Купе'), ('wagon', 'Универсал'), ('hatchback', 'Хэтчбек')], max_length=20)),
                ('volume', models.DecimalField(decimal_places=1, max_digits=4)),
                ('fuel_type', models.CharField(choices=[('petrol', 'Бензин'), ('diesel', 'Дизель'), ('hybrid', 'Гибрид'), ('electric', 'Электро')], max_length=20)),
                ('drive_type', models.CharField(choices=[('fwd', 'Передний'), ('rwd', 'Задний'), ('awd', 'Полный')], max_length=20)),
                ('transmission', models.CharField(choices=[('auto', 'Автомат'), ('manual', 'Механика'), ('cvt', 'Вариатор')], max_length=20)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.brand')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.carmodel')),
                ('complete_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.completeset')),
            ],
        ),
    ]
